env:
  global:
    - DOMAIN=travis.com
services:
  - redis-server
  - sqlite
language: python
python:
  - "3.6"
install:
  - pip install --no-cache-dir -r demo/requirements.txt
script:
  - python demo/manage.py test shop.tests
