version: '3'

services:
  redis:
    image: "redis:alpine"

  nginx:
    container_name: nginx-container
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # linux
      - api_data:/docker_api
      - ./log:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - ./demo/static:/docker_api/static
      - ./demo/media:/docker_api/media
      # mac
      #- /usr/local/etc/nginx/
    depends_on:
      - web

  web:
    container_name: api-container
    build: ./demo
    restart: always
    command: uwsgi --ini uwsgi.ini
    volumes:
      - api_data:/docker_api
      - ./demo/static:/docker_api/static
      - ./demo/media:/docker_api/media
    depends_on:
      - redis 

  migration_and_run_worker:
    container_name: celery
    environment:
      - DJANGO_SETTINGS_MODULE=demo.settings.prod
    build: ./demo
    volumes:
      - api_data:/docker_api
    command: bash -c "python manage.py migrate && celery -A demo worker -l info"
    depends_on:
      - redis
volumes:
  api_data:
